AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  HelloJuliaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello.handler
      Runtime: provided
      CodeUri: ./src
      Description: ''
      MemorySize: 512
      Timeout: 30
      #Role: arn:aws:iam::1111111:role/LambdaExecRole
      Layers:
        - 'arn:aws:lambda:ap-northeast-1:11111111:layer:JuliaLayer:1'
